### ISSUE TITLE
港澳台有问题

### ISSUE THREAD

**Issue by zhweifeng** [xinjie-just/address-select#1]
港澳台有问题

**Comment by xinjie-just** [comment]
你是指选择最后一级地址吗？应该是没有数据的，如果有条件，可以把数据放到自己的数据库里

**Comment by xinjie-just** [comment]
你是指选择最后一级地址吗？应该是没有数据的，如果有条件，可以把数据放到自己的数据库里

**Comment by xinjie-just** [comment]
问题已修复，当没有街道信息时，显示到区(县)级
