### ISSUE TITLE
请问可以吧街道(乡镇)数据源下载地址给一下吗

### ISSUE THREAD

**Issue by kangzhixin2017** [xinjie-just/address-select#2]

**Comment by xinjie-just** [comment]
先打开获取省市区数据源的地址，[获取省市区](http://passer-by.com/data_location/list.json)，然后找到你想要获取的街道信息属于哪个县（区），如四川成都锦江区，它的 code 是 510104，那获取它下属的街道信息就是 [获取锦江区街道信息](http://passer-by.com/data_location/town/510104.json)。
`{"510104020":"督院街街道","510104021":"盐市口街道","510104022":"春熙路街道","510104023":"书院街街道","510104024":"合江亭街道","510104025":"水井坊街道","510104026":"牛市口街道","510104027":"龙舟路街道","510104028":"双桂路街道","510104029":"莲新街道","510104030":"沙河街道","510104031":"东光街道","510104032":"狮子山街道","510104035":"成龙路街道","510104036":"柳江街道","510104037":"三圣街道"}`
你应该好好看看README.md的说明

**Comment by kangzhixin2017** [comment]
你好，我其实是发现了你的一个BUG。请选择广东省里面的东莞市或者中山市，这两个的下一级地址是没有的。我原本以为是你的地址库有问题，后面排查了一下发现其实是这两个市下面没有区，那么由于你的街道是根据上一级区的code去拿取的，所以导致获取不到街道数据。我自己的程序我是改完了，你有空可以改改你的这个bug。谢谢！

**Comment by xinjie-just** [comment]
感谢反馈

**Comment by xinjie-just** [comment]
选中没有县级行政区域的地址(如东莞、中山)后，显示街道(乡镇)
