### ISSUE TITLE
选择完以后，没有把“市”回显到结果

### ISSUE THREAD

**Issue by Yahome** [xinjie-just/address-select#3]
在city.js的returnData里的rsData加上city属性就可以了

**Comment by xinjie-just** [comment]
你好，我没有测到这个问题，是哪个市没有回显，可以截张图吗

**Comment by Yahome** [comment]
> 你好，我没有测到这个问题，是哪个市没有回显，可以截张图吗

![image](https://user-images.githubusercontent.com/21332415/46248325-87d04f00-c44a-11e8-8178-18659aacdd83.png)

**Comment by xinjie-just** [comment]
感谢反馈，已添加
